import sys
import os, os.path
import subprocess
from distutils.sysconfig import get_config_var
here = os.getcwd()
exe_ext = get_config_var("EXE")

def check_exe(cmd):
    subprocess.check_call([cmd + exe_ext])
os.chdir("examples")
os.chdir("hello")
subprocess.check_call([sys.executable, "setup.py", "build"])
subprocess.check_call([sys.executable, "test.py"])
os.chdir("..")
os.chdir("arraytest")
subprocess.check_call([sys.executable, "setup.py", "build"])
subprocess.check_call([sys.executable, "test.py"])
os.chdir("..")
os.chdir("inherit")
subprocess.check_call([sys.executable, "setup.py", "build"])
subprocess.check_call([sys.executable, "test.py"])
os.chdir("..")
os.chdir("rawexample")
subprocess.check_call([sys.executable, "setup.py", "build"])
subprocess.check_call([sys.executable, "test.py"])
os.chdir("..")
os.chdir("testdll")
subprocess.check_call([sys.executable, "setup.py", "build"])
subprocess.check_call([sys.executable, "test.py"])
os.chdir("..")
os.chdir("pyind")
subprocess.check_call([sys.executable, "setup.py", "pydexe"])
subprocess.check_call(["pyind" + exe_ext])
os.chdir("..")
os.chdir("pyd_unittests")
subprocess.check_call([sys.executable, "setup.py", "pydexe"])
check_exe("class_wrap")
check_exe("def")
check_exe("embedded")
check_exe("func_wrap")
check_exe("make_object")
check_exe("pydobject")
check_exe("struct_wrap")

