from os.path import abspath 
Import('*')
print (env27).subst_path(infra)
env27_c = env27.Clone(DFLAGS = ["-c", "-J"+join("infrastructure", "deimos","python")], DPATH=".")

env27_c.Program("deimos/python/Python.d");
